### ISSUE TITLE
Concatenation of fixtures for different directories

### ISSUE THREAD

**Issue by christopherlb** [willbryant/fixation#5]
At current, when defining a fixture, the last file found overrides all other fixtures in totality. This leads to unnecessary duplication of fixtures in the last folder.
e.g.
```
paths = [ 'core/fixtures', 'component/fixtures' ]
# core/person.yml
bob:
  name: 'bob'
# component/person.yml
jim:
  name: 'jim'

# Only jim is stored. To access bob, you'd have 
# to copy-paste into the component's yml
```

Use cases for this could be for different engines, requiring different tests, or running different test suites e.g. one for nightly tests, another for TDD.

A method of selectively concatenating fixtures together would solve this.

For example, this could be configured through a 'component/additions' folder.

```
paths = [ 'core/fixtures', 'component/fixtures' ]
additions = [ 'component/additions' ]
# core/fixtures/person.yml
bob:
  name: 'bob'
# component/additions/person.yml
jim:
  name: 'jim'

# jim and bob are both stored
```
